version: '3'
services:
  flask:
    container_name: flask
    ports:
      - "5000:5000"
    build: ./flask
    env_file:
      - .env
    # depends_on:
    #   - rabbitmq

  earning:
    container_name: earning
    build: ./earning
    env_file:
      - .env
    # depends_on:
    #   - rabbitmq

  # rabbitmq:
  #   hostname: rabbitmq
  #   image: rabbitmq:latest
  #   restart: always
  #   environment:
  #       - RABBITMQ_DEFAULT_USER=admin
  #       - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - "5672:5672"
